TARGET := CDEV_903T
obj-m = $(TARGET).o
$(TARGET)-objs = csec_cdev.o

#all:
#	cp ../CCP903_SEC_BASE/Module.symvers $(shell pwd)
#	make -C /lib/modules/$(shell uname -r)/build M=$(shell pwd) modules
#	#make -C /home/zjjin/work/ccfc9000ta/linux-3.4.106.ccore.r1 M=$(shell pwd) modules ARCH=powerpc
#clean:
#	rm -rf *.a *.o *.ko *.mod.c *.mod.o modules.* Mod*

